### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by NaimChowdhury** [KenshiDRK/XiView#1]
Trying to view/cancel any of the icons causes Windower to crash. (First time use after Dec 11 2018 update.)

**Comment by KenshiDRK** [comment]
Make sure you are using lastest version, and you replaced the correct dat. Also try it on vanilla ffxi

**Comment by NaimChowdhury** [comment]
In particular I had Utsusemi: Ichi, Food, and Signet buffs on. Attempting to scroll through them consistently causes Windower to crash. (Just to confirm, I am using the latest version, but I haven't tried vanilla XI yet. For now, as long as I'm not scrolling through my status icons the game runs fine.) Thanks for the incredibly quick reply. I'll let you know if the error is client side by testing another machine at some point.
