### ISSUE TITLE
June 10, 2024 version update seems to have caused an issue

### ISSUE THREAD

**Issue by RShakleford** [KenshiDRK/XiView#13]
The newest update uninstalled XIView automatically and if reinstalled will now cause the game to instantly crash when you try to open the menu/check equipment.

**Comment by guppysb** [comment]
I agree, same issue when I try to open the item menu. Even with debugging enabled for Ashita, I am unable to capture the issue of the crash in the logs.

**Comment by KenshiDRK** [comment]
Update is up.

**Comment by RShakleford** [comment]
Awesome. Keep up the fantastic work!
